server:
  port: 8081
spring:
  application:
    name: swp
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

  # thymeleaf
  thymeleaf:
    prefix: classpath:WEB-INF/views/
    suffix: .html
    #设置html标签非严格校验
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    #开发阶段务必关闭缓存 (=false)
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  redis:
      database: 0 #数据库索引，默认是0
      host: 127.0.0.1 #节点地址-必填
      port: 6379 #节点端口-必填
      password: wjl1234567890 #密码，默认无
      timeout: 3000 #连接超时时间，模式1000ms
      lettuce:
        pool:
          max-active: 10 #连接池最大连接数，默认是10（使用负值表示没有限制）
          max-wait: -1 #连接池最大阻塞等待时间,默认-1（使用负值表示没有限制）
          max-idle: 3 #连接池中的最大空闲连接，默认是3
          min-idle: 0 #连接池中的最小空闲连接，默认是0

# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 5
      # 配置最大线程数
      max_pool_size: 30
      # 配置队列大小
      queue_capacity: 9999
      # 配置线程池中的线程的名称前缀
      name.prefix: swp-task
